### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by gre** [glslio/transitions.glsl.io#60]
Here is GLSL.io next milestones:
- [x] **v1.2**: Polish/bugfixes + Gallery features (unpublished list, pagination) + small features
- [x] **v1.3: Technical release**: Refactoring to React + Play 2.3
- [x] **v1.4: Custom textures**: Support for custom `sampler2D` uniforms (user texture) – GLSL.io may provides a bunch of default textures. (? user could customise images)
- [x] **v1.5: Help the Transition Developer**: display FPS? customize bezier curves, transition duration / delay (must be in an "Advanced" window) + user feedback for transition validity (on client side, validate if a transition is valid) + Transition view only page?
- [x] **v1.6: Ease web integration of transitions**: Twitter Card + embed using iframe (customize width,height,images,uniforms in the url) + Download Transitions + minification of GLSL (+ transitions snapshots)
- [ ] **More responsive**: Improve mobile support, change the editor layout if width < threshold (+ other ratio)
- [ ] **Stars**: an user can star a transition (using Gist Stars)
- [ ] **Sorting in the gallery** with different criteria (top | recent | both (_default_))
- [x] **Author page** (shows transitions created by a given user) (+ introducing user badges?)
- [ ] **Contribution across users**: fork a transition to "contribute to it". This fork don't appear in gallery but can be then merged by the author (like a PR). This will allows to keep improving transitions and sharing glsl tips between users. Would be great to notify users too.
- [ ] **Server side rendering**: pre-render thumbnails (improve gallery perfs + to use for twitter card) + validation (+ user feedback?)

**This list could change in the future depending on user needs and new ideas.
We plan to make new releases each week.**
